### ISSUE TITLE
Problem with plot_title

### ISSUE THREAD

**Issue by jtr13** [hrbrmstr/statebins#16]
If I try adding a plot title to the help example:
```
data(USArrests)
USArrests$state <- rownames(USArrests)
statebins(USArrests, value_col="Assault", text_color="black", font_size=3,
          plot_title = "1973 Assault arrests",
          legend_title = "Assault", legend_position="bottom")
```

I get no plot, no error, and the following output in the console:
```
TableGrob (2 x 1) "arrange": 2 grobs
    z     cells    name                grob
    1 (1-1,1-1) arrange      gtable[layout]
sub 2 (2-2,1-1) arrange text[GRID.text.716]
```
Is anyone else having this problem, or maybe something with my setup?

**Comment by jtr13** [comment]
Never mind, working with the dev version and all is good.  When will I learn?

**Comment by hrbrmstr** [comment]
been having issues with getting pkg updates on CRAN in the past 2 months. things that work on winbuilder, travis and rhub get into some kind of weird zone on CRAN. I'll see if I can re-submit this soon (though I still can't reproduce CRAN's errors in any other environment).
