### ISSUE TITLE
possible to add a line chart to the statebins 

### ISSUE THREAD

**Issue by ericpgreen** [hrbrmstr/statebins#19]
Is it possible to add a line chart to the statebins as shown in this JHU plot?

https://coronavirus.jhu.edu/data/new-cases-50-states

![Screen Shot 2020-05-31 at 12 12 37 PM](https://user-images.githubusercontent.com/546433/83682059-61fd3500-a5b1-11ea-9673-7f5c069aa6b9.png)

**Comment by jtrim-ons** [comment]
@ericpgreen is https://github.com/hafen/geofacet what you need?

**Comment by ericpgreen** [comment]
yep, very slick.
