### ISSUE TITLE
warning: `show_guide` has been deprecated

### ISSUE THREAD

**Issue by haroldgil** [hrbrmstr/statebins#5]
Hi there,

I'm trying to recreate the CDC State FluView map you created using statebins() in your cdcfluview GitHub repo example code (I've made no significant changes). I get the following warning:

Warning: `show_guide` has been deprecated. Please use `show.legend` instead.

Looking at the [statebins.R](https://github.com/hrbrmstr/statebins/blob/master/R/statebins.R) file, I see that there are 3 lines where show_guide=FALSE is specified. I imagine that replacing this with show.legend=FALSE will eliminate this warning.

**Comment by hrbrmstr** [comment]
#ty for the heads up on this. If you’d like to take a stab at the changes
(they do appear to be just what you indicated) and do a PR I’d gladly
accept (also add yourself to the DESCRIPTION as a contributor). No worries
if not and I’ll try to get to it soon.

**Comment by haroldgil** [comment]
I think I did the pull and merge request correctly. Thanks!
